@startuml

class App {
    --Properties--
    -TopLevel:TopLevel
    +Initialize()
    +OnFrameworkInitializationCompleted()
    --ViewModel event handlers--
    - ViewModel_LoadGame(sender: EventArgs, e: EventArgs)
    --Model event handlers--
    - Model_GameOver(sender: EventArgs, e: EventArgs)
}

class BomberViewModel{}

class BomberModel{

}

App o.. "0..1\n-viewModel" BomberViewModel
App o.. "0..1\n-model" BomberModel
@enduml