@startuml
actor Játékos

(Lép) as stepPlayer

Játékos -- stepPlayer
Játékos -- (Bombát rak)
Játékos -- (Új játék)
Játékos -- (Játék szüneteltetése)
Játékos -- (Játék folytatása)
Játékos -- (Kilépés)

(Új játék) ..> stepPlayer : <<precedes>>
(Új játék) ..> (Bombát rak) : <<precedes>>
(Játék szüneteltetése) ..> (Játék folytatása) : <<precedes>

@enduml